# Generated by Django 6.0.4 on 2026-05-13 17:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipping_address',
            field=models.TextField(blank=True, null=True, verbose_name='Delivery Address'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='destination',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='origin',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Ordered', 'Ordered'), ('Dispatched', 'Dispatched'), ('Shipped', 'Shipped'), ('In Transit', 'In Transit'), ('Arrived', 'Arrived at Hub'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered')], default='Pending', max_length=50),
        ),
        migrations.CreateModel(
            name='ShipmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('location', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tracking.shipment')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
