# Generated by Django 6.0.4 on 2026-04-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=200, verbose_name='Origin')),
                ('destination', models.CharField(max_length=200, verbose_name='Destination')),
                ('full_name', models.CharField(max_length=150, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('loading_date', models.DateField(verbose_name='Requested Loading Date')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Additional Message')),
                ('status', models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('Quoted', 'Quoted'), ('Closed', 'Closed')], default='New', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Quote Request',
                'verbose_name_plural': 'Quote Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
